step_config:
  - kind: <%= GlobalConstant::WorkflowStep.grant_eth_stake_currency_init%>
    weight: 20
    group: 0
  - kind: <%= GlobalConstant::WorkflowStep.grant_eth%>
    weight: 20
    group: 1
  - kind: <%= GlobalConstant::WorkflowStep.verify_grant_eth%>
    weight: 20
    group: 1
  - kind: <%= GlobalConstant::WorkflowStep.grant_stake_currency%>
    weight: 20
    group: 2
  - kind: <%= GlobalConstant::WorkflowStep.verify_grant_stake_currency%>
    weight: 20
    group: 2

group_config:
  0:
    display_text: 'Starting grant Eth'
    name: "S&M Start"
  1:
    display_text: 'Grant eth started'
    name: 'Eth started'
  2:
    display_text: 'Grant stake currency started'
    name: 'Stake currency started'