step_config:
  - kind: 'stPrimeStakeAndMintInit'
    weight: 5
    group: 0
  - kind: 'stPrimeApprove'
    weight: 5
    group: 0
  - kind: 'simpleTokenStake'
    weight: 10
    group: 1
  - kind: 'checkApproveStatus'
    weight: 10
    group: 1
  - kind: 'checkStakeStatus'
    weight: 10
    group: 1
  - kind: 'fetchStakeIntentMessageHash'
    weight: 10
    group: 1
  - kind: 'commitStateRoot'
    weight: 10
    group: 2
  - kind: 'updateCommittedStateRootInfo'
    weight: 10
    group: 2
  - kind: 'proveGatewayOnCoGateway'
    weight: 10
    group: 2
  - kind: 'checkProveGatewayStatus'
    weight: 10
    group: 3
  - kind: 'confirmStakeIntent'
    weight: 10
    group: 3
  - kind: 'checkConfirmStakeStatus'
    weight: 10
    group: 3
  - kind: 'progressStake'
    weight: 10
    group: 3
  - kind: 'checkProgressStakeStatus'
    weight: 10
    group: 3
  - kind: 'progressMint'
    weight: 10
    group: 3
  - kind: 'checkProgressMintStatus'
    weight: 10
    group: 3

group_config:
  0:
    display_text: 'Starting st prime stake and mint'
    name: "ST Prime S&M Start"
  1:
    display_text: 'Deploying organization'
    name: 'Organization Deployment'
  2:
    display_text: 'Deploying Gateway and Co-gateway'
    name: 'Gateway, CoGateway Deployment'
  3:
    display_text: 'Set gateway and co-gateway'
    name: 'Set Gateway, Co-Gateway'
